# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  registryName: "sllr2wa5ppkoompnpreg.azurecr.io"
  repositoryName: "techexcel/dotnetcoreapp"
  dockerFolderPath: "./src/Application/src/RazorPagesTestSample"
  tag: ${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      working-directory: ./src/Application/src/RazorPagesTestSample
      run: dotnet restore
    
    - name: Build
      working-directory: ./src/Application/src/RazorPagesTestSample
      run: dotnet build --no-restore
    
    - name: Test
      working-directory: ./src/Application/tests/RazorPagesTestSample.Tests
      run: dotnet test --no-build --verbosity normal
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to container registry
      run: docker login ${{ env.registryName }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} --build-arg build_version=${{ env.tag }} ${{ env.dockerFolderPath }}

    - name: Push Docker image
      run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

    - name: Deploy to the Azure Web App (Dev)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sllr2wa5ppkoo-dev'
        images: "sllr2wa5ppkoompnpreg.azurecr.io/techexcel/dotnetcoreapp:${{ env.tag }}"