name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
    - name: Echo first string
      run: echo "Step 1 complete!"

    - name: Echo second string
      run: echo "Step 2 complete!"
